### ISSUE TITLE
10.0.0-rc.2 no longer working with Gatsby

### ISSUE THREAD

**Issue by thomkrupa** [preactjs/preact#1921]
Hey,

I updated preact to the latest version (from `rc.1`) in my gatsby project, and a very weird thing happened. There are no errors during the build nor the runtime, but yet the app doesn't re-render fully during the routing for some reason.

So if I click on a link, I go to /page-2/ but the content doesn't update.

Here is the demo:
- repo: https://github.com/thomkrupa/gatsby-starter-default (2 branches with different preact version)
- `rc.1`: https://preact-10-0-0-rc-1--youthful-jones-c0352b.netlify.com/
- `rc.2`: https://preact-10-0-0-rc-2--youthful-jones-c0352b.netlify.com

please click on `Go to page 2` and see what's happening - on the rc.1 everything works just fine. On the rc.2 URL is updating, but the content does not.

I have no idea how to further debug this issue, so any help would be much appreciated. Thank you!

**Comment by JoviDeCroock** [comment]
Hey, this has been fixed on master. We'll release a new version asap since it fixes your issue (which is pretty critical)

Thanks for the good issue report.

**Comment by JoviDeCroock** [comment]
We've published rc.3 with the fix!

**Comment by thomkrupa** [comment]
@JoviDeCroock I updated preact to rc.3 and seems it didn't fix the issue.
demo: https://preact-10-0-0-rc-3--youthful-jones-c0352b.netlify.com/

**Comment by JoviDeCroock** [comment]
It does work in gatsby develop right? Because I pulled in your repository and ran yarn dev and it worked

**Comment by thomkrupa** [comment]
@JoviDeCroock `gatsby-plugin-preact` uses react in dev mode. React is aliased to preact only for production. (source: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-preact/src/gatsby-node.js).

**Comment by JoviDeCroock** [comment]
Yes found out as well, I found the fix that works with the production mode. PR'ed it now, this will probably need some discussion tomorrow with some fellow team-members but we'll tackle your issue asap.

**Comment by thomkrupa** [comment]
Thank you! Really appreciate it!
