### ISSUE TITLE
Missing key when using rc-animate

### ISSUE THREAD

**Issue by dignifiedquire** [preactjs/preact#615]
It seems there is some difference between React and Preact when using rc-animate. It seems similar to https://github.com/developit/preact/issues/155 but still appears in the latest version.

I have been using https://github.com/react-component/collapse without issues (following the simple example in the readme) with React, but when switching over to Preact I get the following error thrown

<img width="892" alt="screen shot 2017-03-29 at 23 43 17" src="https://cloud.githubusercontent.com/assets/790842/24478009/86814202-14d9-11e7-9afd-217a564386df.png">

<img width="744" alt="screen shot 2017-03-29 at 23 44 16" src="https://cloud.githubusercontent.com/assets/790842/24478042/a9f82b1a-14d9-11e7-97f3-28b141f568f3.png">

The key is not explicitly set here it seems: https://github.com/react-component/collapse/blob/master/src/Panel.jsx#L63 but I am guessing for single elements React sets the key automatically?

**Comment by developit** [comment]
Hmm, that's quite odd, I can't think of a reason why React would be needing to set a key automatically. Maybe it defaults to numeric?

**Comment by dignifiedquire** [comment]
What's also interesting is that, even if I manually a key it doesn' throw anymore but the animation is actually not happening anymore.

**Comment by developit** [comment]
Hey @dignifiedquire - this is fixed by @hassanbazzi's work in #629. Working to release 8.1.0 with that fix today.

**Comment by dignifiedquire** [comment]
@developit great to hear thank you! I will try it out once its out asap

**Comment by developit** [comment]
Should be fixed in `8.1.0`.

**Comment by dignifiedquire** [comment]
I am afraid the error persists with `8.1.0`, exact same issue as originally posted

**Comment by hassanbazzi** [comment]
It seems fixed to me. Are you sure you upgraded? Can you provide the error?

**Comment by thysultan** [comment]
React sets keys to preserve order, i.e when conditionally rendering between `null`, int keys might conflict with user keys when some keys are set and some aren't, maybe floating point ints. In this case i think the error is from rc-animate and not React, the lib is validating that children indeed do have keys and since react auto inserts keys when omitted it works with React.

**Comment by developit** [comment]
Ah yeah, sounds like we were following a red herring.  We'll need `preact-compat` to emulate the default integer key behavior (which makes me sad).

**Comment by dignifiedquire** [comment]
I run into yet another issue with the joys of libraries depending on reacts behaviour for how the children methods behave, so I started work implementing them here: https://github.com/developit/preact-compat/pull/400

**Comment by AmareshB** [comment]
I encountered this issue while rendering select tags with "" as value and "None" as display properties.
I don't see the issue when I replace the "" value with "none" (some random value).

Please tell me, if there is a better work around.

**Comment by JoviDeCroock** [comment]
Let's track this in https://github.com/preactjs/preact/issues/3403
